version: "3.9"
services:
  karate-test:
    image: karateudemy
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - ./target:/usr/src/app/target
      - ~/.m2:/root/.m2
    command: mvn test
